[package]
name = "rust-interpolation"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.19"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "my_benchmark"
harness = false